language: python
dist: bionic
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
before_install:
- >
  pip install --upgrade pip mypy 'attrs==19.2.0'
  -r https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-rpdk/master/requirements.txt
install:
- pip install . src/
env:
  global:
  - AWS_DEFAULT_REGION="us-east-1"
script:
- pre-commit run --all-files
jobs:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - stage: "integ python 3.6"
    language: python
    python: "3.6"
    script:
      - OUT=$(pwd)
      - cd src/
      - python3 setup.py sdist
      - cp dist/*.tar.gz "$OUT"
      - rm -r dist/
      - cd ..
      - ls -la
      - DIR=$(mktemp -d)
      - cp cloudformation-cli-python-lib-2.1.1.tar.gz "$DIR"
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n1\ny" | cfn init -vv
      - ls -la
      - mypy src/aws_foo_bar/ --strict --implicit-reexport
      - cfn submit --dry-run
  - stage: "integ python 3.7"
    language: python
    python: "3.7"
    script:
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n2\ny" | cfn init -vv
      - ls -la
      - mypy src/aws_foo_bar/ --strict --implicit-reexport
