version: 0.2
phases:
  install:
    commands:
      # make sure pip/setuptools/wheel is up to date, awscli for SDK patching
      - pip install --upgrade pip setuptools wheel awscli -r requirements.txt
      - aws configure add-model --service-model "file://$CODEBUILD_SRC_DIR_RPDK/cloudformation-2010-05-15.normal.json" --service-name cloudformation
  build:
    commands:
      # install aws-cloudformation-rpdk-python-plugin and rpdk core
      - pip install "$CODEBUILD_SRC_DIR_RPDK" .
      # run lints/tests
      - pre-commit run --all-files
      # end-to-end test
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - |
        echo "AWS::Foo::Bar
        1" | cfn-cli init -vv # python3.6
      - ls -la
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - |
        echo "AWS::Foo::Bar
        2" | cfn-cli init -vv # python3.7
      - ls -la
