version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - >
        pip install --upgrade pip setuptools wheel mypy
        -r https://raw.githubusercontent.com/aws-cloudformation/aws-cloudformation-rpdk/master/requirements.txt
  build:
    commands:
      - pip install . src/
      # run lints/tests
      - pre-commit run --all-files
      # end-to-end test
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n1\nn" | cfn init -vv # python3.6
      - ls -la
      - mypy src/aws_foo_bar/ --strict --implicit-reexport
      - DIR=$(mktemp -d)
      - cd "$DIR"
      - ls -la
      - printf "AWS::Foo::Bar\n2\nn" | cfn init -vv # python3.7
      - ls -la
      - mypy src/aws_foo_bar/ --strict --implicit-reexport
